### ISSUE TITLE
Jitsi Meet

### ISSUE THREAD

**Issue by polluks** [classilla/tenfourfox#404]
I cannot open the Device settings in https://meet.jit.si
my camera works with macam.

**Comment by classilla** [comment]
Jitsi is WebRTC based, and we don't support WebRTC. I don't have any plans to do so currently since it would require a lot of work to perform well.

Also, as a general note, please see the front page: end user support requests should be going through [Tenderapp](https://tenfourfox.tenderapp.com/), not here. Thanks!
