### ISSUE TITLE
Endian-neutral fixes

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#452]
For Riccardo's special project.

**Comment by rmottola** [comment]
Check if Font Table is endian dependent. First attempt is to suppose so.

```
/Users/multix/Documents/code/tenfourfox/gfx/thebes/gfxMacPlatformFontList.mm:491:2: 
error: #error needs GetFontTable fast path needs little endian version
#error needs GetFontTable fast path needs little endian version
```


It is *possible* that GetFontTable already works on Intel. What I don't
know is if the uint32_t tag you get is little endian or big endian. If it's
already in big endian format even on Intel (because TrueType FourCC tags are
big endian), then it will "just work." If not, you will need to byteswap
aTag before you start comparing it (see "ASSUME THAT aTag is already big
endian" as well as aTableTag and "// ASSUME THAT aTableTag is already big
endian"). You may not know this until you try to build it and fonts don't
work.

**Comment by rmottola** [comment]
Disable ION (--disable-ion)

**Comment by rmottola** [comment]
CTYPES have issues building on intel on older MacOS due to libffi.

--disable-ctypes temporarily

**Comment by rmottola** [comment]
Disable SKIA - does not build

**Comment by classilla** [comment]
see also https://github.com/classilla/tenfourfox/pull/455

**Comment by classilla** [comment]
see also #475

**Comment by classilla** [comment]
Dropping as a metabug in favour of PRs
