### ISSUE TITLE
SafeBrowsing issue with eBay

### ISSUE THREAD

**Issue by classilla** [classilla/tenfourfox#619]
In private windows with tracking protection on, most eBay assets do not load. In a debug build:

```
[19792] WARNING: Could not find prefix in PrefixSet during noise lookup: file /Volumes/BruceDeuce/src/tenfourfox/toolkit/components/url-classifier/Classifier.cpp, line 729
[19792] WARNING: NS_ENSURE_SUCCESS(rv, rv) failed with result 0x80004005: file /Volumes/BruceDeuce/src/tenfourfox/toolkit/components/url-classifier/nsUrlClassifierDBService.cpp, line 328
```

**Comment by classilla** [comment]
See @OlgaTPark 's report in https://tenfourfox.tenderapp.com/discussions/problems/9010-tenfourfox-and-ebay

**Comment by OlgaTPark** [comment]
Hello,   

I have finally found how to solve this issue.   
The solution resides in the following Firefox patch: <https://hg.mozilla.org/mozreview/gecko/rev/37c01bf2ca007527910a1256444ebd6c9d114aae> (which solves [M1258041](https://bugzilla.mozilla.org/show_bug.cgi?id=1258041) — changing the settings referred in the patch into `about:config` is already enough).  After applying this patch you maybe need to reset the `browser.safebrowsing.provider.mozilla.nextupdatetime` `about:config` setting to force the browser to reload the online data.   

I also looked at some other BMO bugs that « could » be related to the previous one (or at least, that improves the way safe browsing is handled): 
 - [M1285428 — Some tables in `urlclassifier.trackingWhitelistTable` may be missed during table registration](https://bugzilla.mozilla.org/show_bug.cgi?id=1285428) which fixes some muddled lines of code concerning tracking lists unregistration/registration;
 - [M1274685 — Unowned Safe Browsing tables break list updates](https://bugzilla.mozilla.org/show_bug.cgi?id=1274685) which also affects TenFourFox;

I tested the three previously mentionned patches in a local Intel build.   

Just for completeness, you don't need [M1292728 (testcase failure)](https://bugzilla.mozilla.org/show_bug.cgi?id=1292728) which isn't in code nor [M1281083 — Changing the `urlclassifier.*Table prefs` doesn't take effect before the next browser restart](https://bugzilla.mozilla.org/show_bug.cgi?id=1281083) (unless you don't want to restart the browser).   

I hope this could help!

**Comment by classilla** [comment]
Have you committed this to your branch? I'll take that diff if you have (you don't need to do it as a PR), or otherwise I'll port. Thank you very much for the detective work.

**Comment by OlgaTPark** [comment]
Sorry, I haven't committed this anywhere.   

Fortunately, the patches are easy to import.  Those are:   
 - <https://hg.mozilla.org/mozilla-central/rev/fff9d624dca2> which solves [M1258041](https://bugzilla.mozilla.org/show_bug.cgi?id=1258041) (note that the link in my previous comment wrongly refers to the `mozreview` branch instead of the `mozilla-central` branch — the only difference is the addition of `test-forbid-simple` into the `urlclassifier.disallow_completions` pref in `mozilla-central`);   
 - (optional) <https://hg.mozilla.org/mozilla-central/rev/4287a45df22d> for [M1285428](https://bugzilla.mozilla.org/show_bug.cgi?id=1285428);   
 - (optional) <https://hg.mozilla.org/mozilla-central/rev/2df25135bcd3> for [M1274685](https://bugzilla.mozilla.org/show_bug.cgi?id=1274685);   
 - (optional) <https://hg.mozilla.org/mozilla-central/rev/30700073705d> which is the testcase for [M1274685](https://bugzilla.mozilla.org/show_bug.cgi?id=1274685);   

…And you're welcome for keeping our old Mac<sub>s</sub> relevant!

**Comment by classilla** [comment]
stickin'
